dist: trusty
sudo: true
language: python
python:
  - "3.4"
before_install:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/bin
install:
  - pip install --upgrade -r pip_runtime_requirements.txt
  - pip install --upgrade -r pip_test_requirements.txt
  - pip install --upgrade -r pip_admin_requirements.txt
before_script:
  - npm install --save-dev mocha
script:
  - python -m pytest tests_cfp --cov accuconf_cfp
  - python -m pytest tests_cfp__selenium --cov accuconf_cfp
  - python -m pytest tests_api --cov accuconf_api
  - npm test
#after_success:
#  coveralls
