login_menu_item = '<a href="/login" title="Login">Login</a>'
register_menu_item = '<a href="/register" title="Register">Register</a>'
registration_update_menu_item = '<a href="/registration_update" title="Registration Update">Registration Update</a>'
submit_menu_item = '<a href="/submit" title="Submit">Submit</a>'
my_proposals_menu_item = '<a href="/myproposals" title="My Proposals">My Proposals</a>'
